### PR TITLE
M2 / ARM builds

### PR DESCRIPTION
**Pull request by nein09**
I'm trying a private image out (pushed to my own Docker repo) right now and  it's working great. I'll edit the GitHub action here too, if this looks good.

### CODE REVIEW

**Comment by nein09** [comment]
I thought Alpine wouldn't work for ARM64 but that turns out to be an issue specific to a different stack on Alpine (NodeJS) - Golang seems to be fine!

**Comment by nein09** [comment]
However, it turns out that chrome-headless-shell is doing miserably on ARM64, so I'll see what I can do about that..

**Comment by valentinedwv** [comment]
> However, it turns out that chrome-headless-shell is doing miserably on ARM64, so I'll see what I can do about that..

Don't worry, headless  doing miserable on AMD64.  wondering if browser less/chrome is a something to try: https://hub.docker.com/r/browserless/chrome

**Comment by nein09** [comment]
Hmm, it looks like Browserless does support chromedp (as a Beta, but it does it): https://docs.browserless.io/docs/go.html

**Review by fils — APPROVED** [review]
cool!  anxious to hear how it goes!

**Pull request merged**
