### PR TITLE
Fix delay option

### PR DESCRIPTION
**Pull request by nein09**
This is a step on the way to doing https://github.com/gleanerio/gleaner/issues/27

While looking into indexing options, I noticed that no files were summoned when I specified a delay in the gleaner config yaml. I realized that this was because of a code branching error - the `if` statement branch that sets the thread count to 1 if a delay is specified accidentally bypassed the rest of the summoner code.

This fix closes that metaphorical curly brace and adds tests for the delay / thread count interaction logic.

### CODE REVIEW

**Comment by nein09** [comment]
I just realized that I put this up but forgot to request any reviews on it! It's ready for people to look at.

**Comment by nein09** [comment]
@fils @valentinedwv I'm about ready to open a pull request for a fix for https://github.com/gleanerio/gleaner/issues/27 - and it's built on top of this one. 

If someone has time today to look at this one, that'd be great; otherwise, I can close it and open a larger one. But it may be easier to look at them in sequence, just so you're looking at smaller sets of changes.

**Review by valentinedwv — APPROVED** [review]
Looks fine.

**Comment by nein09** [comment]
Thank you!

**Pull request merged**
